# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='timestamp',
        ),
    ]
